### ISSUE TITLE
create a physical volume

### ISSUE THREAD

**Issue by laurentgay-atosibm** [aix-chef/aixlvm#1]
As a chef administrator, I want to be guaranteed that a physical volume exist with correct attribute.

Chef receive should be:
#### Actions

<table>
  <tr>
    <th>Action</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>:create</td>
    <td>(default) Creates or modify a physical volume</td>
  </tr>
</table>

#### Parameters

<table>
  <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Example</th>
    <th>Default</th>
  </tr>
  <tr>
    <td>name</td>
    <td>(required) The device to create the new physical volume on</td>
    <td><tt>'hdisk2'</tt></td>
    <td></td>
  </tr>
  <tr>
    <td>allocatable</td>
    <td>Value of attribute "allocatable"</td>
    <td><tt>false</tt></td>
    <td>true</td>
  </tr>
</table>

#### Examples

```
aixlvm_physical_volume 'hdisk2' do
        allocatable  true
        action :create
end
```

=> Failure if disk name doesn't exist.

**Comment by jez-w** [comment]
Physical volumes are automatically detected, named, and made available by AIX through the `cfgmgr` command (run at boot time or manually). There is not a create PV command in AIX.  Given this, is a "create" provider necessary for physical volumes?

Modifying the attributes of a PV only has meaning once it is part of a volume group

**Comment by laurentgay-atosibm** [comment]
So, what sort of action is needed by Chef about Physical Volumes ?

**Comment by laurentgay-atosibm** [comment]
I close this feature if no needs
