### ISSUE TITLE
create a volume group

### ISSUE THREAD

**Issue by laurentgay-atosibm** [aix-chef/aixlvm#2]
As a chef administrator, I want to ensure that a volume group exists and is varied on with list the specified disks (physical volumes) and attributes. If the volume group is a new volume group, then it will be created as a **scalable** volume group.

Chef receive should be:
#### Actions

<table>
  <tr>
    <th>Action</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>:create</td>
    <td>(default) Creates or modify a volume group</td>
  </tr>
  <tr>
    <td>:add</td>
    <td>Adds a physical volume to a volume group</td>
  </tr>
</table>

#### Parameters

<table>
  <tr>
    <th>Attribute</th>
    <th>Description</th>
    <th>Example</th>
    <th>Default</th>
  </tr>
  <tr>
    <td>name</td>
    <td>(optional) Name of the volume group</td>
    <td><tt>'datavg'</tt></td>
    <td>system generated</td>
  </tr>
  <tr>
    <td>physical_volumes</td>
    <td>(required) The device or list of devices to use as physical volumes (if they haven't already been initialized as physical volumes, they will be initialized automatically)</td>
    <td><tt>['hdisk0', 'hdisk1']</tt></td>
    <td></td>
  </tr>
  <tr>
    <td>use_as_hot_spare</td>
    <td>(optional)Sets the sparing characteristics of the physical volume such that it can be used as a hot spare. Legal values are "y" or "n". "y" marks the disk as a hot spare within the volume group it belongs to. "n" removes the disk from the hot spare pool for the volume group.</td>
    <td><tt>y</tt></td>
    <td><tt>n</tt></td>
  </tr>
  <tr>
    <td>mirror_pool_name</td>
    <td>(optional)Assigns or reassigns the disk to the named mirror pool. The mirror pool is created if it does not exist already Mirror pool names can only contain alphanumeric characters, may not be longer than 15 characters, must be unique in the volume group.</td>
    <td><tt>copy0pool</tt></td>
    <td>none</td>
  </tr>
</table>

#### Examples

Create a volume group called `datavg` comprising 3 disks and assign them to a mirror pool.

```
aixlvm_volume_group 'datavg' do
        physical_volumes ['hdisk1', 'hdisk2', 'hdisk3']
        mirror_pool_name   'copy0pool'
        action :create
end
```

Add a disk as a hot spare to the same `datavg` volume group

```
aixlvm_volume_group 'datavg' do
        physical_volumes ['hdisk4']
        use_as_hot_spare   'y'
        action :add
end
```
### Behaviour
- If the volume group does not exist a **scalable** volume group will be created as specified
- If the volume group exists it will be modified to reflect the specified parameters. The type of the volume group, normal, big or scalable, will not be modified.
  - Physical volumes will be added to or removed from the volume group
### Error cases
- One or more of the specified physical volume names do not exist
- One or more of the specified physical volumes are use in a different volume group
- One or more of the specified physical volumes are managed by third-party volume manager
- Illegal mirror pool name
- The block sizes of all the specified physical volumes are not identical
- The volume group already exists with a different physical partition size

**Comment by laurentgay-atosibm** [comment]
**questions ?**:
- How to know if a physical volume is managed by third-party volume manager ?
- How to know the block sizes of a specified physical volume ?
- max_physical_volumes: it's a number max of PP on physical_volume or volume group?

**Comment by jez-w** [comment]
As far as I am able to ascertain there is not an AIX command to display the block size of a pv.

**Comment by jez-w** [comment]
I have made several changes to the use case. 

I propose that for new volume groups are created as scalable volume groups. Existing volume groups should be unchanged.

With just a :create verb, I cannot see how to add a disk as a hot-spare. I have suggested an :add verb, but am open to other suggestions.

I have added an optional mirror-pool attribute.

See page 340 of: http://public.dhe.ibm.com/systems/power/docs/aix/72/baseadmndita_pdf.pdf

**Comment by laurentgay-atosibm** [comment]
For "block size" control, I remove it on our implementation: if problem, creation will fail.
=> error case 4 should be deprecated.

Ok for me to create volume groups as scalable volume groups.

In the spirit of Chef, a recipe don't realize an short action, but assure that a configuration need is respected.
So, :create or :add is not perfect because they suppose an initial state. 
May be :check or :set will be better.

> I have added an optional mirror-pool attribute.

forgot it?

**Comment by laurentgay-atosibm** [comment]
We don't manage "physical_partition_size" and "max_physical_volumes" ?
What is their default value, so?

**Comment by laurentgay-atosibm** [comment]
If we have the :add action, can we have the :remove action?

**Comment by laurentgay-atosibm** [comment]
What argument for use_as_hot_spare?
In "man mkvg", I don't have 'spare' or 'hot'

**Comment by jez-w** [comment]
To designate a disk as a hot spare use `chvg`

**Comment by jez-w** [comment]
`max_physical_volumes` was an idea to choose which type of volume group to create, `default, big`, or `scalable`. We will just create scalable volume groups.

The `mkvg` command determines the correct partition size (`-s`) and factor (`-t`). In the interests of simplicity I suggest that we use this value. The admin can manually change this with `chvg` if required. The number of partitions is only specified for scalable volume groups.

**Comment by jez-w** [comment]
Use the `lqueryvg -Atp <pv>` command to determine the physical block size. Works on AIX 7.1 and later.

**Comment by laurentgay-atosibm** [comment]
I study the "pool mirror" feature.
=> http://www-01.ibm.com/support/docview.wss?uid=isg3T1019574

If I have understand this logic, we assign a different pool for each disk(or set of disk) to use it in Logical Volume for "copy" featuring.

So, with this configuration of Volume Group, all disks have same "pool mirror name", so it will not be possible to assign different by copy in Logical Volume
