### ISSUE TITLE
rename a volume group

### ISSUE THREAD

**Issue by laurentgay-atosibm** [aix-chef/aixlvm#5]
As a chef administrator, I want to be guaranteed that a old volume group (if exist) is rename to another name (if not exist).

Chef receive should be:
#### Actions

<table>
  <tr>
    <th>Action</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>:rename</td>
    <td>Rename a volume group</td>
  </tr>
</table>

#### Parameters

<table>
  <tr>
    <th>Attribute</th>
    <th>Description</th>
    <th>Example</th>
    <th>Default</th>
  </tr>
  <tr>
    <td>name</td>
    <td>(required) Old name of the volume group</td>
    <td><tt>'bacon'</tt></td>
    <td></td>
  </tr>
  <tr>
    <td>new_name</td>
    <td>(required) New name of the volume group</td>
    <td><tt>'patatos'</tt></td>
    <td></td>
  </tr>
</table>

#### Examples

```
aixlvm_volume_group 'datavg' do
        new_name 'bigdatavg'
        action :rename
end
```

=> No action if old name of volume group doesn't exist before
=> No action if new name of volume group exists before

**Comment by jez-w** [comment]
This is a disruptive operation - the hosted filesystems have to be unmounted and the volume group varied off. I don't think that this is an operation that is required in the first release.

**Comment by laurentgay-atosibm** [comment]
Yes, I have hesitate to add this user story.
So, I close it
