### ISSUE TITLE
defrag a filesystem

### ISSUE THREAD

**Issue by laurentgay-atosibm** [aix-chef/aixlvm#7]
As a chef administrator, I want to be guaranteed that a filesystem is defrag.

Chef receive should be:
#### Actions

<table>
  <tr>
    <th>Action</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>:defrag</td>
    <td>Defrag a filesystem</td>
  </tr>
</table>

#### Parameters

<table>
  <tr>
    <th>Attribute</th>
    <th>Description</th>
    <th>Example</th>
    <th>Default</th>
  </tr>
  <tr>
    <td>name</td>
    <td>(name attribute) Name of the filesystem</td>
    <td><tt>bacon</tt></td>
    <td></td>
  </tr>
</table>

#### Examples

```
aixlvm_filesystem `/data1` do
        action :defrag
end
```
### Error cases
- Filesystem does not exist.
- Filesystem mounted in read-only
- The filesystem is not a JFS2 filesystem

**Comment by jez-w** [comment]
Changed the action to `defragfs` (from `defrag`) to underline that the action applies only to filesystems not logical or physical volumes.

Added an error case where the filesystem is mounted read-only, and the filesystem is not jfs2

The defragfs command is slow against a jfs2 filesystem with a snapshot.
